### ISSUE TITLE
Amount of shares not correct

### ISSUE THREAD

**Issue by PhillipRt** [tfabritius/pr#129]
Hello,

I have noticed, that the amount of shares I hold in some securities after the PP Sync is too high. I assume that some, but not all, sell transactions didn't get synced.

**Comment by tfabritius** [comment]
Thanks for testing and trying it out.

Unfortunately, the information you provided is not sufficient to track down the problem. Can you share the portfolio? Or (even better) create a minimal example to reproduce the problem?
