### ISSUE TITLE
Prisma errors building docker image

### ISSUE THREAD

**Issue by FinkeFlo** [tfabritius/pr#154]
Hello,

i just wanted to test teh app but failed to run the docker on my raspberry pi.

First issue was taht i needed to increase the network-timeout for the yarn install command. 

after i solved this i now have the following issue. It looks like there is an error with the DB?
Could may someone help me? 

pi@raspberrypi:/media/usbstick/pr $ docker build . -f Dockerfile
Sending build context to Docker daemon  1.095MB
Step 1/20 : FROM node:14 AS builder
 ---> d55eec34ac24
Step 2/20 : WORKDIR /app
 ---> Using cache
 ---> 36b142f09c08
Step 3/20 : COPY package.json yarn.lock ./
 ---> Using cache
 ---> f4685b7b67f9
Step 4/20 : COPY api/package.json api/
 ---> Using cache
 ---> 6cfff37b652b
Step 5/20 : COPY web/package.json web/
 ---> Using cache
 ---> f3c8a15860ca
Step 6/20 : RUN yarn install --frozen-lockfile --network-timeout 300000
 ---> Using cache
 ---> aba49b5d90eb
Step 7/20 : COPY api api
 ---> Using cache
 ---> 2a12947565af
Step 8/20 : RUN yarn api build
 ---> Running in 91ba09194416
yarn run v1.22.5
$ yarn workspace pr-api build
$ rimraf dist
$ nest build
src/auth/auth.service.ts:2:10 - error TS2305: Module '"@prisma/client"' has no exported member 'User'.
2 import { User } from '@prisma/client'
src/auth/bearer-session.strategy.ts:4:10 - error TS2305: Module '"@prisma/client"' has no exported member 'User'.
4 import { User } from '@prisma/client'
src/auth/local.strategy.ts:4:10 - error TS2305: Module '"@prisma/client"' has no exported member 'User'.
4 import { User } from '@prisma/client'
src/auth/sessions/sessions.controller.ts:9:10 - error TS2305: Module '"@prisma/client"' has no exported member 'User'.
9 import { User } from '@prisma/client'
src/auth/sessions/sessions.service.ts:3:10 - error TS2305: Module '"@prisma/client"' has no exported member 'User'.
3 import { User, Session } from '@prisma/client'
src/auth/sessions/sessions.service.ts:3:16 - error TS2305: Module '"@prisma/client"' has no exported member 'Session'.
3 import { User, Session } from '@prisma/client'
src/auth/users/users.service.ts:6:10 - error TS2305: Module '"@prisma/client"' has no exported member 'User'.
6 import { User } from '@prisma/client'
src/currencies/currencies.conversion.service.ts:7:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Prisma'.
7 import { Prisma } from '@prisma/client'
src/currencies/currencies.service.ts:3:10 - error TS2305: Module '"@prisma/client"' has no exported member 'ExchangeratePrice'.
3 import { ExchangeratePrice, Prisma } from '@prisma/client'
src/currencies/currencies.service.ts:3:29 - error TS2305: Module '"@prisma/client"' has no exported member 'Prisma'.
3 import { ExchangeratePrice, Prisma } from '@prisma/client'
src/currencies/dto/convert.currencies.dto.ts:2:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Prisma'.
2 import { Prisma } from '@prisma/client'
src/currencies/price.entity.ts:2:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Prisma'.
2 import { Prisma } from '@prisma/client'
src/portfolios/accounts/accounts.kpis.service.ts:2:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Prisma'.
2 import { Prisma } from '@prisma/client'
src/portfolios/accounts/accounts.service.ts:6:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Account'.
6 import { Account } from '@prisma/client'
src/portfolios/dto/CreateUpdatePortfolioSecurityPrice.dto.ts:2:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Prisma'.
2 import { Prisma } from '@prisma/client'
src/portfolios/dto/CreateUpdateTransaction.dto.ts:2:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Prisma'.
2 import { Prisma } from '@prisma/client'
src/portfolios/portfolios.service.ts:2:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Portfolio'.
2 import { Portfolio } from '@prisma/client'
src/portfolios/securities/prices/price.entity.ts:3:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Prisma'.
3 import { Prisma } from '@prisma/client'
src/portfolios/securities/prices/prices.service.ts:2:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Prisma'.
2 import { Prisma } from '@prisma/client'
src/portfolios/securities/securities.kpis.service.ts:2:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Prisma'.
2 import { Prisma, TransactionType } from '@prisma/client'
src/portfolios/securities/securities.kpis.service.ts:2:18 - error TS2305: Module '"@prisma/client"' has no exported member 'TransactionType'.
2 import { Prisma, TransactionType } from '@prisma/client'
src/portfolios/securities/securities.service.ts:6:10 - error TS2305: Module '"@prisma/client"' has no exported member 'PortfolioSecurity'.
6 import { PortfolioSecurity, Prisma } from '@prisma/client'
src/portfolios/securities/securities.service.ts:6:29 - error TS2305: Module '"@prisma/client"' has no exported member 'Prisma'.
6 import { PortfolioSecurity, Prisma } from '@prisma/client'
src/portfolios/transactions/transaction.entity.ts:2:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Prisma'.
2 import { Prisma } from '@prisma/client'
src/portfolios/transactions/transactions.service.ts:6:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Prisma'.
6 import { Prisma, Transaction, TransactionUnit } from '@prisma/client'
src/portfolios/transactions/transactions.service.ts:6:18 - error TS2305: Module '"@prisma/client"' has no exported member 'Transaction'.
6 import { Prisma, Transaction, TransactionUnit } from '@prisma/client'
src/portfolios/transactions/transactions.service.ts:6:31 - error TS2305: Module '"@prisma/client"' has no exported member 'TransactionUnit'.
6 import { Prisma, Transaction, TransactionUnit } from '@prisma/client'
src/portfolios/transactions/transactions.service.ts:219:17 - error TS2339: Property 'type' does not exist on type 'unknown'.
219           right.type,
src/portfolios/transactions/transactions.service.ts:220:17 - error TS2339: Property 'amount' does not exist on type 'unknown'.
220           right.amount,
src/portfolios/transactions/transactions.service.ts:221:17 - error TS2339: Property 'currencyCode' does not exist on type 'unknown'.
221           right.currencyCode,
src/portfolios/transactions/transactions.service.ts:222:17 - error TS2339: Property 'originalAmount' does not exist on type 'unknown'.
222           right.originalAmount,
src/portfolios/transactions/transactions.service.ts:223:17 - error TS2339: Property 'originalCurrencyCode' does not exist on type 'unknown'.
223           right.originalCurrencyCode,
src/portfolios/transactions/transactions.service.ts:224:17 - error TS2339: Property 'exchangeRate' does not exist on type 'unknown'.
224           right.exchangeRate,
src/portfolios/transactions/transactions.service.ts:231:45 - error TS2339: Property 'id' does not exist on type 'unknown'.
231         id: { in: unmatchedDbs.map((u) => u.id) },
src/portfolios/transactions/unit.entity.ts:3:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Prisma'.
3 import { Prisma } from '@prisma/client'
src/securities/dto/security.taxonomy.dto.ts:2:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Prisma'.
2 import { Prisma } from '@prisma/client'
src/securities/securities.service.ts:9:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Prisma'.
9 import { Prisma } from '@prisma/client'
src/stats/stats.controller.ts:19:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Prisma'.
19 import { Prisma } from '@prisma/client'
src/taxonomies/taxonomies.controller.ts:20:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Prisma'.
20 import { Prisma } from '@prisma/client'
src/utils/decimal.parser.ts:1:10 - error TS2305: Module '"@prisma/client"' has no exported member 'Prisma'.
1 import { Prisma } from '@prisma/client'
Found 40 error(s).
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /opt/yarn-v1.22.5/lib/cli.js build
Directory: /app/api
Output:
info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
The command '/bin/sh -c yarn api build' returned a non-zero code: 1

**Comment by tfabritius** [comment]
This issue should be fixed by 1e9c141e00f570b7f4934807a841e7cff9d55dc3. Please be aware, that the app is not ready for testing yet.
